package historiadeusuarioemcodigo.contratodaataderegistrodeprecorefatorado;

public interface ContratoDaAtaDeRegistroDePrecoRepositorio {
    void adicioinar(ContratoDaAtaDeRegistroDePreco contratoDaAtaDeRegistroDePreco);
}
